export const TYPES_TEMPLATE = `/* Auto-generated by sdkforge. Do not edit. */

{{#each namedTypes}}
{{{declaration}}}

{{/each}}`

export const RESOURCE_TEMPLATE = `/* Auto-generated by sdkforge. Do not edit. */

import { request, type CallOptions } from '../runtime';
{{#if importedTypes.length}}
import type {
{{#each importedTypes}}
    {{this}},
{{/each}}
} from '../types';
{{/if}}
import type { SDKClient } from '../client';

export class {{className}} {
    constructor(private readonly client: SDKClient) {}

{{#each methods}}{{{body}}}{{#unless @last}}

{{/unless}}{{/each}}
}
`

export const CLIENT_TEMPLATE = `/* Auto-generated by sdkforge. Do not edit. */

import type { ClientConfig } from './runtime';
{{#each resources}}
import { {{className}} } from './resources/{{fileName}}';
{{/each}}

export interface SDKClientConfig extends ClientConfig {}

export class SDKClient {
    readonly config: SDKClientConfig;
{{#each resources}}
    readonly {{name}}: {{className}};
{{/each}}

    constructor(config: SDKClientConfig = {}) {
        this.config = { baseURL: '{{baseUrl}}', ...config };
{{#each resources}}
        this.{{name}} = new {{className}}(this);
{{/each}}
    }
}
`

export const INDEX_TEMPLATE = `/* Auto-generated by sdkforge. Do not edit. */

export { SDKClient } from './client';
export type { SDKClientConfig } from './client';
export { SDKError } from './runtime';
export type { CallOptions, ClientConfig, RequestOptions } from './runtime';
export type * from './types';
`

export const PACKAGE_JSON_TEMPLATE = `{
  "name": "{{name}}",
  "version": "{{version}}",
  "description": "{{description}}",
  "type": "module",
  "main": "./dist/index.js",
  "module": "./dist/index.js",
  "types": "./dist/index.d.ts",
  "exports": {
    ".": {
      "types": "./dist/index.d.ts",
      "import": "./dist/index.js"
    }
  },
  "files": ["dist"],
  "scripts": {
    "build": "tsc"
  },
  "engines": {
    "node": ">=18"
  },
  "author": "{{author}}",
  "license": "{{license}}",
  "devDependencies": {
    "typescript": "^5.5.0"
  }
}
`

export const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "target": "ES2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": ["ES2022", "DOM"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "declaration": true,
    "outDir": "dist",
    "rootDir": "src"
  },
  "include": ["src/**/*"]
}
`

export const README_TEMPLATE = `# {{name}}

{{description}}

## Installation

\`\`\`bash
npm install {{name}}
\`\`\`

## Usage

\`\`\`ts
import { SDKClient } from '{{name}}';

const client = new SDKClient({
    apiKey: process.env.API_KEY,
    baseURL: '{{baseUrl}}',
});
{{#if exampleCall}}

{{{exampleCall}}}
{{/if}}
\`\`\`

## Error handling

\`\`\`ts
import { SDKError } from '{{name}}';

try {
    {{#if exampleResource}}await client.{{exampleResource}}.{{exampleMethod}}({{exampleArgs}});{{else}}// ...{{/if}}
} catch (err) {
    if (err instanceof SDKError) {
        console.error(\\\`HTTP \\\${err.status}: \\\${err.statusText}\\\`, err.body);
    }
    throw err;
}
\`\`\`

## Cancellation

\`\`\`ts
const controller = new AbortController();
{{#if exampleResource}}const promise = client.{{exampleResource}}.{{exampleMethod}}({{exampleArgs}}{{exampleArgsComma}}{ signal: controller.signal });
{{else}}// pass { signal: controller.signal } as the last argument{{/if}}
controller.abort();
\`\`\`

---

Generated by [sdkforge](https://github.com/example/sdkforge).
`
